# -*- coding: utf-8 -*-
"""App.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lHYiARLuQ0FnitHFEzyRjjsP14GTStkB
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import cohere
# 
# co = cohere.Client("your-cohere-api-key")
# 
# STYLE_PRESETS = {
#     "Funny": "a humorous and witty tone",
#     "Poetic": "a poetic and artistic style",
#     "Instagram": "social-media friendly tone with emojis and hashtags",
#     "Professional": "a formal, concise, and technical tone",
#     "Child-friendly": "simple language, suitable for young children"
# }
# 
# def rephrase(prompt):
#     response = co.generate(
#         model="command-r-plus",
#         prompt=prompt,
#         max_tokens=60,
#         temperature=0.8
#     )
#     return response.generations[0].text.strip()
# 
# st.title("🖼️ Caption Style Personalizer")
# 
# caption = st.text_input("Original Caption", "a dog sitting on the beach")
# mode = st.radio("Choose Mode:", ["Simple", "Advanced"])
# 
# if mode == "Simple":
#     style = st.selectbox("Choose a style", list(STYLE_PRESETS.keys()))
#     desc = STYLE_PRESETS[style]
#     prompt = f"Rewrite this image caption in {desc}:\n\nOriginal: '{caption}'\n\nRewritten:"
# else:
#     custom = st.text_area("Enter custom instruction")
#     prompt = f"{custom}\n\nOriginal Caption: '{caption}'\n\nRewritten:"
# 
# if st.button("Generate"):
#     result = rephrase(prompt)
#     st.success(result)
#